prokka /home/meiker/git/genomes/lactococcus_00001.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00001 --prefix lactococcus_00001 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00002.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00002 --prefix lactococcus_00002 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00003.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00003 --prefix lactococcus_00003 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00004.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00004 --prefix lactococcus_00004 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00005.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00005 --prefix lactococcus_00005 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00006.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00006 --prefix lactococcus_00006 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00007.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00007 --prefix lactococcus_00007 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00008.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00008 --prefix lactococcus_00008 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00009.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00009 --prefix lactococcus_00009 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00010.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00010 --prefix lactococcus_00010 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00011.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00011 --prefix lactococcus_00011 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00012.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00012 --prefix lactococcus_00012 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00013.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00013 --prefix lactococcus_00013 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00014.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00014 --prefix lactococcus_00014 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00015.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00015 --prefix lactococcus_00015 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00016.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00016 --prefix lactococcus_00016 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00017.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00017 --prefix lactococcus_00017 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00018.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00018 --prefix lactococcus_00018 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00019.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00019 --prefix lactococcus_00019 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00020.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00020 --prefix lactococcus_00020 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00021.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00021 --prefix lactococcus_00021 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00022.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00022 --prefix lactococcus_00022 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00023.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00023 --prefix lactococcus_00023 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00024.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00024 --prefix lactococcus_00024 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00025.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00025 --prefix lactococcus_00025 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00026.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00026 --prefix lactococcus_00026 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00027.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00027 --prefix lactococcus_00027 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00028.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00028 --prefix lactococcus_00028 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00029.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00029 --prefix lactococcus_00029 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00030.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00030 --prefix lactococcus_00030 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00031.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00031 --prefix lactococcus_00031 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00032.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00032 --prefix lactococcus_00032 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00033.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00033 --prefix lactococcus_00033 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00034.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00034 --prefix lactococcus_00034 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00035.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00035 --prefix lactococcus_00035 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00036.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00036 --prefix lactococcus_00036 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00037.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00037 --prefix lactococcus_00037 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00038.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00038 --prefix lactococcus_00038 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00039.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00039 --prefix lactococcus_00039 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00040.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00040 --prefix lactococcus_00040 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00041.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00041 --prefix lactococcus_00041 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00042.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00042 --prefix lactococcus_00042 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00043.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00043 --prefix lactococcus_00043 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00044.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00044 --prefix lactococcus_00044 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00045.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00045 --prefix lactococcus_00045 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00046.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00046 --prefix lactococcus_00046 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00047.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00047 --prefix lactococcus_00047 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00048.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00048 --prefix lactococcus_00048 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00049.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00049 --prefix lactococcus_00049 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00050.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00050 --prefix lactococcus_00050 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00051.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00051 --prefix lactococcus_00051 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00052.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00052 --prefix lactococcus_00052 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00053.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00053 --prefix lactococcus_00053 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00054.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00054 --prefix lactococcus_00054 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00055.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00055 --prefix lactococcus_00055 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00056.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00056 --prefix lactococcus_00056 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00057.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00057 --prefix lactococcus_00057 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00058.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00058 --prefix lactococcus_00058 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00059.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00059 --prefix lactococcus_00059 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00060.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00060 --prefix lactococcus_00060 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00061.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00061 --prefix lactococcus_00061 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00062.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00062 --prefix lactococcus_00062 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00063.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00063 --prefix lactococcus_00063 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00064.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00064 --prefix lactococcus_00064 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00065.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00065 --prefix lactococcus_00065 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00066.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00066 --prefix lactococcus_00066 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00067.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00067 --prefix lactococcus_00067 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00068.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00068 --prefix lactococcus_00068 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00069.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00069 --prefix lactococcus_00069 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00070.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00070 --prefix lactococcus_00070 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00071.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00071 --prefix lactococcus_00071 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00072.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00072 --prefix lactococcus_00072 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00073.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00073 --prefix lactococcus_00073 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00074.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00074 --prefix lactococcus_00074 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00075.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00075 --prefix lactococcus_00075 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00076.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00076 --prefix lactococcus_00076 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00077.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00077 --prefix lactococcus_00077 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00078.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00078 --prefix lactococcus_00078 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00079.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00079 --prefix lactococcus_00079 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00080.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00080 --prefix lactococcus_00080 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00081.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00081 --prefix lactococcus_00081 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00082.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00082 --prefix lactococcus_00082 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00083.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00083 --prefix lactococcus_00083 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00084.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00084 --prefix lactococcus_00084 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00085.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00085 --prefix lactococcus_00085 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00086.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00086 --prefix lactococcus_00086 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00087.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00087 --prefix lactococcus_00087 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00088.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00088 --prefix lactococcus_00088 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00089.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00089 --prefix lactococcus_00089 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00090.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00090 --prefix lactococcus_00090 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00091.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00091 --prefix lactococcus_00091 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00092.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00092 --prefix lactococcus_00092 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00093.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00093 --prefix lactococcus_00093 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00094.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00094 --prefix lactococcus_00094 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00095.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00095 --prefix lactococcus_00095 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00096.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00096 --prefix lactococcus_00096 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00097.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00097 --prefix lactococcus_00097 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00098.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00098 --prefix lactococcus_00098 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00099.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00099 --prefix lactococcus_00099 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00100.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00100 --prefix lactococcus_00100 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00101.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00101 --prefix lactococcus_00101 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00102.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00102 --prefix lactococcus_00102 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00103.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00103 --prefix lactococcus_00103 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00104.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00104 --prefix lactococcus_00104 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00105.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00105 --prefix lactococcus_00105 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00106.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00106 --prefix lactococcus_00106 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00107.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00107 --prefix lactococcus_00107 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00108.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00108 --prefix lactococcus_00108 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00109.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00109 --prefix lactococcus_00109 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00110.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00110 --prefix lactococcus_00110 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00111.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00111 --prefix lactococcus_00111 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00112.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00112 --prefix lactococcus_00112 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00113.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00113 --prefix lactococcus_00113 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00114.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00114 --prefix lactococcus_00114 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00115.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00115 --prefix lactococcus_00115 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00116.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00116 --prefix lactococcus_00116 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00117.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00117 --prefix lactococcus_00117 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00118.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00118 --prefix lactococcus_00118 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00119.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00119 --prefix lactococcus_00119 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00120.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00120 --prefix lactococcus_00120 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00121.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00121 --prefix lactococcus_00121 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00122.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00122 --prefix lactococcus_00122 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00123.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00123 --prefix lactococcus_00123 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00124.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00124 --prefix lactococcus_00124 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00125.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00125 --prefix lactococcus_00125 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00126.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00126 --prefix lactococcus_00126 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00127.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00127 --prefix lactococcus_00127 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00128.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00128 --prefix lactococcus_00128 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00129.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00129 --prefix lactococcus_00129 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00130.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00130 --prefix lactococcus_00130 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00131.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00131 --prefix lactococcus_00131 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00132.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00132 --prefix lactococcus_00132 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00133.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00133 --prefix lactococcus_00133 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00134.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00134 --prefix lactococcus_00134 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00135.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00135 --prefix lactococcus_00135 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00136.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00136 --prefix lactococcus_00136 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00137.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00137 --prefix lactococcus_00137 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00138.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00138 --prefix lactococcus_00138 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00139.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00139 --prefix lactococcus_00139 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00140.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00140 --prefix lactococcus_00140 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00141.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00141 --prefix lactococcus_00141 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00142.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00142 --prefix lactococcus_00142 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00143.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00143 --prefix lactococcus_00143 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00144.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00144 --prefix lactococcus_00144 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00145.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00145 --prefix lactococcus_00145 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00146.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00146 --prefix lactococcus_00146 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00147.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00147 --prefix lactococcus_00147 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00148.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00148 --prefix lactococcus_00148 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00149.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00149 --prefix lactococcus_00149 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00150.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00150 --prefix lactococcus_00150 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00151.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00151 --prefix lactococcus_00151 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00152.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00152 --prefix lactococcus_00152 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00153.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00153 --prefix lactococcus_00153 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00154.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00154 --prefix lactococcus_00154 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00155.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00155 --prefix lactococcus_00155 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00156.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00156 --prefix lactococcus_00156 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00157.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00157 --prefix lactococcus_00157 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00158.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00158 --prefix lactococcus_00158 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00159.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00159 --prefix lactococcus_00159 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00160.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00160 --prefix lactococcus_00160 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00161.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00161 --prefix lactococcus_00161 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00162.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00162 --prefix lactococcus_00162 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00163.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00163 --prefix lactococcus_00163 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00164.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00164 --prefix lactococcus_00164 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00165.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00165 --prefix lactococcus_00165 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00166.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00166 --prefix lactococcus_00166 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00167.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00167 --prefix lactococcus_00167 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00168.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00168 --prefix lactococcus_00168 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00169.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00169 --prefix lactococcus_00169 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00170.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00170 --prefix lactococcus_00170 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00171.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00171 --prefix lactococcus_00171 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00172.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00172 --prefix lactococcus_00172 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00173.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00173 --prefix lactococcus_00173 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00174.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00174 --prefix lactococcus_00174 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00175.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00175 --prefix lactococcus_00175 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00176.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00176 --prefix lactococcus_00176 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00177.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00177 --prefix lactococcus_00177 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00178.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00178 --prefix lactococcus_00178 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00179.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00179 --prefix lactococcus_00179 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00180.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00180 --prefix lactococcus_00180 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00181.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00181 --prefix lactococcus_00181 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00182.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00182 --prefix lactococcus_00182 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00183.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00183 --prefix lactococcus_00183 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00184.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00184 --prefix lactococcus_00184 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00185.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00185 --prefix lactococcus_00185 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00186.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00186 --prefix lactococcus_00186 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00187.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00187 --prefix lactococcus_00187 --genus lactococcus 
prokka /home/meiker/git/genomes/lactococcus_00188.fna --outdir /home/meiker/git/prokka_annotation/lactococcus_00188 --prefix lactococcus_00188 --genus lactococcus 
