cp /home/git/data/prokka_annotation/lactococcus_00137/lactococcus_00137.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00180/lactococcus_00180.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00188/lactococcus_00188.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00187/lactococcus_00187.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00092/lactococcus_00092.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00017/lactococcus_00017.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00020/lactococcus_00020.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00059/lactococcus_00059.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00173/lactococcus_00173.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00005/lactococcus_00005.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00178/lactococcus_00178.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00001/lactococcus_00001.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00009/lactococcus_00009.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_09919/streptococcus_09919.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/floricoccus_00001/floricoccus_00001.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00084/streptococcus_00084.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11903/streptococcus_11903.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00011/streptococcus_00011.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11883/streptococcus_11883.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00014/streptococcus_00014.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00022/streptococcus_00022.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00018/streptococcus_00018.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03931/streptococcus_03931.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03956/streptococcus_03956.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03957/streptococcus_03957.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07831/streptococcus_07831.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07817/streptococcus_07817.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00001/streptococcus_00001.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00015/streptococcus_00015.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00021/streptococcus_00021.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03942/streptococcus_03942.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03953/streptococcus_03953.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03954/streptococcus_03954.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03955/streptococcus_03955.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07824/streptococcus_07824.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07832/streptococcus_07832.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07834/streptococcus_07834.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02605/streptococcus_02605.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11933/streptococcus_11933.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00331/streptococcus_00331.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01815/streptococcus_01815.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07823/streptococcus_07823.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11884/streptococcus_11884.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00053/streptococcus_00053.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11927/streptococcus_11927.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00102/streptococcus_00102.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11868/streptococcus_11868.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_06022/streptococcus_06022.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11836/streptococcus_11836.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00195/streptococcus_00195.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_09930/streptococcus_09930.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00944/streptococcus_00944.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02159/streptococcus_02159.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04286/streptococcus_04286.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_05954/streptococcus_05954.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04015/streptococcus_04015.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_09918/streptococcus_09918.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02064/streptococcus_02064.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00186/streptococcus_00186.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01723/streptococcus_01723.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01804/streptococcus_01804.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01809/streptococcus_01809.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02063/streptococcus_02063.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02071/streptococcus_02071.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04284/streptococcus_04284.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04390/streptococcus_04390.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04418/streptococcus_04418.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_05950/streptococcus_05950.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_08003/streptococcus_08003.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00073/streptococcus_00073.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11864/streptococcus_11864.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00070/streptococcus_00070.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11831/streptococcus_11831.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01727/streptococcus_01727.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07986/streptococcus_07986.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04401/streptococcus_04401.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04403/streptococcus_04403.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01671/streptococcus_01671.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00026/streptococcus_00026.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00029/streptococcus_00029.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_09936/streptococcus_09936.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_10375/streptococcus_10375.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07971/streptococcus_07971.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07844/streptococcus_07844.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11862/streptococcus_11862.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02944/streptococcus_02944.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00115/streptococcus_00115.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00563/streptococcus_00563.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04630/streptococcus_04630.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_06016/streptococcus_06016.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07833/streptococcus_07833.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11960/streptococcus_11960.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11844/streptococcus_11844.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11845/streptococcus_11845.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00175/streptococcus_00175.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00167/streptococcus_00167.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07856/streptococcus_07856.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02148/streptococcus_02148.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00091/streptococcus_00091.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00088/streptococcus_00088.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11918/streptococcus_11918.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07872/streptococcus_07872.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07904/streptococcus_07904.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_09913/streptococcus_09913.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_05958/streptococcus_05958.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00105/streptococcus_00105.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00016/streptococcus_00016.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00012/streptococcus_00012.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_05696/streptococcus_05696.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00010/streptococcus_00010.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11929/streptococcus_11929.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07954/streptococcus_07954.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11838/streptococcus_11838.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03973/streptococcus_03973.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04001/streptococcus_04001.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00192/streptococcus_00192.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_06722/streptococcus_06722.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07820/streptococcus_07820.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_10696/streptococcus_10696.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_06464/streptococcus_06464.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00081/streptococcus_00081.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00550/streptococcus_00550.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00551/streptococcus_00551.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01936/streptococcus_01936.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_02356/streptococcus_02356.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_05798/streptococcus_05798.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_06203/streptococcus_06203.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_06223/streptococcus_06223.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_08288/streptococcus_08288.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_09004/streptococcus_09004.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00063/streptococcus_00063.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07932/streptococcus_07932.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03979/streptococcus_03979.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_04012/streptococcus_04012.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_00023/streptococcus_00023.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07830/streptococcus_07830.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_08877/streptococcus_08877.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_09948/streptococcus_09948.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00055/lactococcus_00055.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00127/lactococcus_00127.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00181/lactococcus_00181.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00186/lactococcus_00186.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00184/lactococcus_00184.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/lactococcus_00183/lactococcus_00183.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11902/streptococcus_11902.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11955/streptococcus_11955.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11840/streptococcus_11840.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_07829/streptococcus_07829.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11854/streptococcus_11854.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11892/streptococcus_11892.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11893/streptococcus_11893.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11908/streptococcus_11908.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11932/streptococcus_11932.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11935/streptococcus_11935.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11942/streptococcus_11942.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11886/streptococcus_11886.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11875/streptococcus_11875.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11919/streptococcus_11919.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11948/streptococcus_11948.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11897/streptococcus_11897.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11947/streptococcus_11947.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11898/streptococcus_11898.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11934/streptococcus_11934.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11872/streptococcus_11872.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11900/streptococcus_11900.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11869/streptococcus_11869.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11944/streptococcus_11944.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11832/streptococcus_11832.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11907/streptococcus_11907.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11946/streptococcus_11946.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_03934/streptococcus_03934.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11876/streptococcus_11876.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11871/streptococcus_11871.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11945/streptococcus_11945.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11899/streptococcus_11899.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11870/streptococcus_11870.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11863/streptococcus_11863.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11904/streptococcus_11904.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11956/streptococcus_11956.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_01814/streptococcus_01814.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11962/streptococcus_11962.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11963/streptococcus_11963.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11964/streptococcus_11964.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11965/streptococcus_11965.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11966/streptococcus_11966.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11967/streptococcus_11967.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11968/streptococcus_11968.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11969/streptococcus_11969.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11970/streptococcus_11970.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11971/streptococcus_11971.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11972/streptococcus_11972.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11973/streptococcus_11973.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11974/streptococcus_11974.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11975/streptococcus_11975.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11976/streptococcus_11976.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11977/streptococcus_11977.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11978/streptococcus_11978.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11979/streptococcus_11979.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11980/streptococcus_11980.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11981/streptococcus_11981.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11982/streptococcus_11982.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11983/streptococcus_11983.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11984/streptococcus_11984.gff /home/meiker/roary/gff_files
cp /home/git/data/prokka_annotation/streptococcus_11985/streptococcus_11985.gff /home/meiker/roary/gff_files
