prokka /home/meiker/genomes/RB-01-S-bovis-NTB2-39468.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11962 --prefix streptococcus_11962 --genus streptococcus
prokka /home/meiker/genomes/RB-02-S-gallolyticus-NTB12.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11963 --prefix streptococcus_11963 --genus streptococcus
prokka /home/meiker/genomes/RB-03-S-bovis-1293.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11964 --prefix streptococcus_11964 --genus streptococcus
prokka /home/meiker/genomes/RB-04-S-macedonicus-CIP105685T.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11965 --prefix streptococcus_11965 --genus streptococcus
prokka /home/meiker/genomes/RB-05-S-bovis-1459.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11966 --prefix streptococcus_11966 --genus streptococcus
prokka /home/meiker/genomes/RB-06-S-macedonicus-ACA-DC-205.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11967 --prefix streptococcus_11967 --genus streptococcus
prokka /home/meiker/genomes/RB-07-S-gallolyticus-NTB1.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11968 --prefix streptococcus_11968 --genus streptococcus
prokka /home/meiker/genomes/RB-08-S-bovis-1067.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11969 --prefix streptococcus_11969 --genus streptococcus
prokka /home/meiker/genomes/RB-09-S-macedonicus-8SP---S-bovis.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11970 --prefix streptococcus_11970 --genus streptococcus
prokka /home/meiker/genomes/RB-10-S-bovis-1361.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11971 --prefix streptococcus_11971 --genus streptococcus
prokka /home/meiker/genomes/RB-11-S-bovis-1364.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11972 --prefix streptococcus_11972 --genus streptococcus
prokka /home/meiker/genomes/RB-12-S-gallolyticus-UCN50.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11973 --prefix streptococcus_11973 --genus streptococcus
prokka /home/meiker/genomes/RB-13-S-bovis-1294.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11974 --prefix streptococcus_11974 --genus streptococcus
prokka /home/meiker/genomes/RB-14-S-bovis-1445.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11975 --prefix streptococcus_11975 --genus streptococcus
prokka /home/meiker/genomes/RB-15-S-gallolyticus-9L-1503-1121-L.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11976 --prefix streptococcus_11976 --genus streptococcus
prokka /home/meiker/genomes/RB-16-S-bovis-1365.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11977 --prefix streptococcus_11977 --genus streptococcus
prokka /home/meiker/genomes/RB-17-S-gallolyticus-subsp-macedonicus-NTB3-.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11978 --prefix streptococcus_11978 --genus streptococcus
prokka /home/meiker/genomes/RB-18-S-bovis-1212.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11979 --prefix streptococcus_11979 --genus streptococcus
prokka /home/meiker/genomes/RB-19-S-gallolyticus-NTB11.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11980 --prefix streptococcus_11980 --genus streptococcus
prokka /home/meiker/genomes/RB-20-S-bovis-1417.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11981 --prefix streptococcus_11981 --genus streptococcus
prokka /home/meiker/genomes/RB-21-S-gallolyticus-NTB4.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11982 --prefix streptococcus_11982 --genus streptococcus
prokka /home/meiker/genomes/RB-22-S-bovis-207.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11983 --prefix streptococcus_11983 --genus streptococcus
prokka /home/meiker/genomes/RB-23-S-bovis-NTB7.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11984 --prefix streptococcus_11984 --genus streptococcus
prokka /home/meiker/genomes/RB-24-S-bovis-992.fasta --outdir /home/meiker/git/prokka_annotation/streptococcus_11985 --prefix streptococcus_11985 --genus streptococcus
