/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Adenylsucc_synt -out /home/meiker/phylo_tree/msa/Adenylsucc_synt -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/ADK -out /home/meiker/phylo_tree/msa/ADK -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/AICARFT_IMPCHas -out /home/meiker/phylo_tree/msa/AICARFT_IMPCHas -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/ATP-synt -out /home/meiker/phylo_tree/msa/ATP-synt -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/ATP-synt_A -out /home/meiker/phylo_tree/msa/ATP-synt_A -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Chorismate_synt -out /home/meiker/phylo_tree/msa/Chorismate_synt -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/EF_TS -out /home/meiker/phylo_tree/msa/EF_TS -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/eIF-1a -out /home/meiker/phylo_tree/msa/eIF-1a -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Exonuc_VII_L -out /home/meiker/phylo_tree/msa/Exonuc_VII_L -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/GrpE -out /home/meiker/phylo_tree/msa/GrpE -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ham1p_like -out /home/meiker/phylo_tree/msa/Ham1p_like -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/IPPT -out /home/meiker/phylo_tree/msa/IPPT -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/OSCP -out /home/meiker/phylo_tree/msa/OSCP -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Pept_tRNA_hydro -out /home/meiker/phylo_tree/msa/Pept_tRNA_hydro -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/PGK -out /home/meiker/phylo_tree/msa/PGK -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/RBFA -out /home/meiker/phylo_tree/msa/RBFA -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/RecO_C -out /home/meiker/phylo_tree/msa/RecO_C -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribonuclease_P -out /home/meiker/phylo_tree/msa/Ribonuclease_P -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L1 -out /home/meiker/phylo_tree/msa/Ribosomal_L1 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L13 -out /home/meiker/phylo_tree/msa/Ribosomal_L13 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L14 -out /home/meiker/phylo_tree/msa/Ribosomal_L14 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L16 -out /home/meiker/phylo_tree/msa/Ribosomal_L16 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L17 -out /home/meiker/phylo_tree/msa/Ribosomal_L17 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L18p -out /home/meiker/phylo_tree/msa/Ribosomal_L18p -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L19 -out /home/meiker/phylo_tree/msa/Ribosomal_L19 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L20 -out /home/meiker/phylo_tree/msa/Ribosomal_L20 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L21p -out /home/meiker/phylo_tree/msa/Ribosomal_L21p -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L22 -out /home/meiker/phylo_tree/msa/Ribosomal_L22 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L23 -out /home/meiker/phylo_tree/msa/Ribosomal_L23 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/ribosomal_L24 -out /home/meiker/phylo_tree/msa/ribosomal_L24 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S3_C -out /home/meiker/phylo_tree/msa/Ribosomal_S3_C -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L5 -out /home/meiker/phylo_tree/msa/Ribosomal_L5 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L2 -out /home/meiker/phylo_tree/msa/Ribosomal_L2 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L27 -out /home/meiker/phylo_tree/msa/Ribosomal_L27 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L27A -out /home/meiker/phylo_tree/msa/Ribosomal_L27A -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L28 -out /home/meiker/phylo_tree/msa/Ribosomal_L28 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L29 -out /home/meiker/phylo_tree/msa/Ribosomal_L29 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L3 -out /home/meiker/phylo_tree/msa/Ribosomal_L3 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L32p -out /home/meiker/phylo_tree/msa/Ribosomal_L32p -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L35p -out /home/meiker/phylo_tree/msa/Ribosomal_L35p -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L4 -out /home/meiker/phylo_tree/msa/Ribosomal_L4 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L6 -out /home/meiker/phylo_tree/msa/Ribosomal_L6 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_L9_C -out /home/meiker/phylo_tree/msa/Ribosomal_L9_C -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S10 -out /home/meiker/phylo_tree/msa/Ribosomal_S10 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S11 -out /home/meiker/phylo_tree/msa/Ribosomal_S11 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S13 -out /home/meiker/phylo_tree/msa/Ribosomal_S13 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S15 -out /home/meiker/phylo_tree/msa/Ribosomal_S15 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S16 -out /home/meiker/phylo_tree/msa/Ribosomal_S16 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S17 -out /home/meiker/phylo_tree/msa/Ribosomal_S17 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S19 -out /home/meiker/phylo_tree/msa/Ribosomal_S19 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S2 -out /home/meiker/phylo_tree/msa/Ribosomal_S2 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S20p -out /home/meiker/phylo_tree/msa/Ribosomal_S20p -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S6 -out /home/meiker/phylo_tree/msa/Ribosomal_S6 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S7 -out /home/meiker/phylo_tree/msa/Ribosomal_S7 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S8 -out /home/meiker/phylo_tree/msa/Ribosomal_S8 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosomal_S9 -out /home/meiker/phylo_tree/msa/Ribosomal_S9 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/Ribosom_S12_S23 -out /home/meiker/phylo_tree/msa/Ribosom_S12_S23 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/RNA_pol_L -out /home/meiker/phylo_tree/msa/RNA_pol_L -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/RNA_pol_Rpb6 -out /home/meiker/phylo_tree/msa/RNA_pol_Rpb6 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/RRF -out /home/meiker/phylo_tree/msa/RRF -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/RsfS -out /home/meiker/phylo_tree/msa/RsfS -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/RuvX -out /home/meiker/phylo_tree/msa/RuvX -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/SecE -out /home/meiker/phylo_tree/msa/SecE -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/SecG -out /home/meiker/phylo_tree/msa/SecG -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/SecY -out /home/meiker/phylo_tree/msa/SecY -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/SmpB -out /home/meiker/phylo_tree/msa/SmpB -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/tRNA-synt_1d -out /home/meiker/phylo_tree/msa/tRNA-synt_1d -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/tRNA_m1G_MT -out /home/meiker/phylo_tree/msa/tRNA_m1G_MT -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/TsaE -out /home/meiker/phylo_tree/msa/TsaE -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/UPF0054 -out /home/meiker/phylo_tree/msa/UPF0054 -maxiters 1 -diags1 -sv
/home/meiker/software/muscle3.8.31_i86linux64 -in /home/meiker/phylo_tree/mfa/YajC -out /home/meiker/phylo_tree/msa/YajC -maxiters 1 -diags1 -sv
