/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Adenylsucc_synt -out /home/meiker/phylo_tree/msa_trimmed/Adenylsucc_synt -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/ADK -out /home/meiker/phylo_tree/msa_trimmed/ADK -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/AICARFT_IMPCHas -out /home/meiker/phylo_tree/msa_trimmed/AICARFT_IMPCHas -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/ATP-synt -out /home/meiker/phylo_tree/msa_trimmed/ATP-synt -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/ATP-synt_A -out /home/meiker/phylo_tree/msa_trimmed/ATP-synt_A -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Chorismate_synt -out /home/meiker/phylo_tree/msa_trimmed/Chorismate_synt -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/EF_TS -out /home/meiker/phylo_tree/msa_trimmed/EF_TS -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/eIF-1a -out /home/meiker/phylo_tree/msa_trimmed/eIF-1a -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Exonuc_VII_L -out /home/meiker/phylo_tree/msa_trimmed/Exonuc_VII_L -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/GrpE -out /home/meiker/phylo_tree/msa_trimmed/GrpE -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ham1p_like -out /home/meiker/phylo_tree/msa_trimmed/Ham1p_like -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/IPPT -out /home/meiker/phylo_tree/msa_trimmed/IPPT -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/OSCP -out /home/meiker/phylo_tree/msa_trimmed/OSCP -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Pept_tRNA_hydro -out /home/meiker/phylo_tree/msa_trimmed/Pept_tRNA_hydro -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/PGK -out /home/meiker/phylo_tree/msa_trimmed/PGK -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/RBFA -out /home/meiker/phylo_tree/msa_trimmed/RBFA -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/RecO_C -out /home/meiker/phylo_tree/msa_trimmed/RecO_C -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribonuclease_P -out /home/meiker/phylo_tree/msa_trimmed/Ribonuclease_P -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L1 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L1 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L13 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L13 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L14 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L14 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L16 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L16 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L17 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L17 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L18p -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L18p -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L19 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L19 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L20 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L20 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L21p -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L21p -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L22 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L22 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L23 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L23 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/ribosomal_L24 -out /home/meiker/phylo_tree/msa_trimmed/ribosomal_L24 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S3_C -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S3_C -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L5 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L5 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L2 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L2 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L27 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L27 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L27A -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L27A -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L28 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L28 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L29 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L29 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L3 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L3 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L32p -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L32p -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L35p -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L35p -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L4 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L4 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L6 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L6 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_L9_C -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_L9_C -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S10 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S10 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S11 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S11 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S13 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S13 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S15 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S15 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S16 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S16 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S17 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S17 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S19 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S19 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S2 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S2 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S20p -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S20p -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S6 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S6 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S7 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S7 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S8 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S8 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosomal_S9 -out /home/meiker/phylo_tree/msa_trimmed/Ribosomal_S9 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/Ribosom_S12_S23 -out /home/meiker/phylo_tree/msa_trimmed/Ribosom_S12_S23 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/RNA_pol_L -out /home/meiker/phylo_tree/msa_trimmed/RNA_pol_L -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/RNA_pol_Rpb6 -out /home/meiker/phylo_tree/msa_trimmed/RNA_pol_Rpb6 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/RRF -out /home/meiker/phylo_tree/msa_trimmed/RRF -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/RsfS -out /home/meiker/phylo_tree/msa_trimmed/RsfS -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/RuvX -out /home/meiker/phylo_tree/msa_trimmed/RuvX -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/SecE -out /home/meiker/phylo_tree/msa_trimmed/SecE -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/SecG -out /home/meiker/phylo_tree/msa_trimmed/SecG -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/SecY -out /home/meiker/phylo_tree/msa_trimmed/SecY -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/SmpB -out /home/meiker/phylo_tree/msa_trimmed/SmpB -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/tRNA-synt_1d -out /home/meiker/phylo_tree/msa_trimmed/tRNA-synt_1d -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/tRNA_m1G_MT -out /home/meiker/phylo_tree/msa_trimmed/tRNA_m1G_MT -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/TsaE -out /home/meiker/phylo_tree/msa_trimmed/TsaE -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/UPF0054 -out /home/meiker/phylo_tree/msa_trimmed/UPF0054 -automated1
/home/meiker/software/trimAl/source/trimal -in /home/meiker/phylo_tree/msa/YajC -out /home/meiker/phylo_tree/msa_trimmed/YajC -automated1
