porthomclBlastParser blastres/streptococcus_02187.tab compliantFasta >> splitSimSeq/streptococcus_02187.ss.tsv
porthomclBlastParser blastres/streptococcus_02194.tab compliantFasta >> splitSimSeq/streptococcus_02194.ss.tsv
porthomclBlastParser blastres/streptococcus_02247.tab compliantFasta >> splitSimSeq/streptococcus_02247.ss.tsv
porthomclBlastParser blastres/streptococcus_02251.tab compliantFasta >> splitSimSeq/streptococcus_02251.ss.tsv
porthomclBlastParser blastres/streptococcus_03403.tab compliantFasta >> splitSimSeq/streptococcus_03403.ss.tsv
porthomclBlastParser blastres/streptococcus_03754.tab compliantFasta >> splitSimSeq/streptococcus_03754.ss.tsv
porthomclBlastParser blastres/streptococcus_03784.tab compliantFasta >> splitSimSeq/streptococcus_03784.ss.tsv
porthomclBlastParser blastres/streptococcus_04093.tab compliantFasta >> splitSimSeq/streptococcus_04093.ss.tsv
porthomclBlastParser blastres/streptococcus_04389.tab compliantFasta >> splitSimSeq/streptococcus_04389.ss.tsv
porthomclBlastParser blastres/streptococcus_04450.tab compliantFasta >> splitSimSeq/streptococcus_04450.ss.tsv
