porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 30
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 31
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 32
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 33
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 34
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 35
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 36
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 37
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 38
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 39
