porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x t
