porthomclBlastParser blastres/streptococcus_01250.tab compliantFasta >> splitSimSeq/streptococcus_01250.ss.tsv
porthomclBlastParser blastres/streptococcus_01255.tab compliantFasta >> splitSimSeq/streptococcus_01255.ss.tsv
porthomclBlastParser blastres/streptococcus_01268.tab compliantFasta >> splitSimSeq/streptococcus_01268.ss.tsv
porthomclBlastParser blastres/streptococcus_01318.tab compliantFasta >> splitSimSeq/streptococcus_01318.ss.tsv
porthomclBlastParser blastres/streptococcus_01540.tab compliantFasta >> splitSimSeq/streptococcus_01540.ss.tsv
porthomclBlastParser blastres/streptococcus_01644.tab compliantFasta >> splitSimSeq/streptococcus_01644.ss.tsv
porthomclBlastParser blastres/streptococcus_01811.tab compliantFasta >> splitSimSeq/streptococcus_01811.ss.tsv
porthomclBlastParser blastres/streptococcus_01946.tab compliantFasta >> splitSimSeq/streptococcus_01946.ss.tsv
porthomclBlastParser blastres/streptococcus_02111.tab compliantFasta >> splitSimSeq/streptococcus_02111.ss.tsv
porthomclBlastParser blastres/streptococcus_02137.tab compliantFasta >> splitSimSeq/streptococcus_02137.ss.tsv
