porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 11
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 12
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 13
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 14
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 15
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 16
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 17
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 18
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 19
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 20
