porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
porthomclBlastParser blastres/s.tab compliantFasta >> splitSimSeq/s.ss.tsv
