porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 0
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 1
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 2
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 3
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 4
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 5
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 6
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 7
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 8
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 9
