porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 40
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 41
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 42
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 43
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 44
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 45
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 46
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 47
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 48
porthomclPairsOrthologs.py -t taxon_list -b besthit -o orthologs -x 49
