porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 20
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 21
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 22
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 23
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 24
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 25
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 26
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 27
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 28
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 29
