porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 51
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 52
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 53
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 54
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 55
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 56
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 57
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 58
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 59
porthomclPairsInParalogs.py -t taxon_list -q paralogTemp -o ogenes -p paralogs -x 60
