porthomclBlastParser blastres/streptococcus_06940.tab compliantFasta >> splitSimSeq/streptococcus_06940.ss.tsv
porthomclBlastParser blastres/streptococcus_06953.tab compliantFasta >> splitSimSeq/streptococcus_06953.ss.tsv
porthomclBlastParser blastres/streptococcus_07601.tab compliantFasta >> splitSimSeq/streptococcus_07601.ss.tsv
porthomclBlastParser blastres/streptococcus_07720.tab compliantFasta >> splitSimSeq/streptococcus_07720.ss.tsv
porthomclBlastParser blastres/streptococcus_08184.tab compliantFasta >> splitSimSeq/streptococcus_08184.ss.tsv
porthomclBlastParser blastres/streptococcus_08215.tab compliantFasta >> splitSimSeq/streptococcus_08215.ss.tsv
porthomclBlastParser blastres/streptococcus_08281.tab compliantFasta >> splitSimSeq/streptococcus_08281.ss.tsv
porthomclBlastParser blastres/streptococcus_08521.tab compliantFasta >> splitSimSeq/streptococcus_08521.ss.tsv
porthomclBlastParser blastres/streptococcus_08768.tab compliantFasta >> splitSimSeq/streptococcus_08768.ss.tsv
porthomclBlastParser blastres/streptococcus_09139.tab compliantFasta >> splitSimSeq/streptococcus_09139.ss.tsv
