porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4867 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4868 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4869 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4870 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4871 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4874 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4875 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4881 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4882 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4883 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4884 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4888 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4889 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4894 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4898 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4900 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4901 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4902 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4904 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4905 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4907 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4911 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4912 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4917 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4919 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4922 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4924 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4925 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4926 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4927 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4930 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4932 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4934 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4939 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4947 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4948 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4950 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4957 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4958 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4961 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4963 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4964 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4966 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4971 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4973 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4978 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4981 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4984 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4985 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4987 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4988 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4989 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4990 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4998 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5000 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5001 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5003 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5004 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5005 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5006 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5007 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5013 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5014 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5015 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5017 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5026 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5027 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5028 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5029 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5031 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5034 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5037 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5038 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5040 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5041 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5045 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5055 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5056 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5057 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5058 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5060 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5063 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5064 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5065 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5071 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5072 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5074 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5075 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5077 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5079 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5080 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5082 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5083 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5085 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5088 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5089 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5090 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5093 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5094 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5095 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5096 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5097 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5098 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5101 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5104 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5105 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5106 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5108 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5110 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5113 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5115 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5121 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5123 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5126 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5128 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5129 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5130 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5132 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5133 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5135 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5136 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5137 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5139 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5143 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5145 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5163 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5167 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5168 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5170 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5174 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5175 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5176 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5179 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5180 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5182 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5186 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5187 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5188 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5190 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5191 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5192 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5195 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5196 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5198 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5201 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5210 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5212 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5215 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5218 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5219 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5224 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5225 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5230 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5232 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5234 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5236 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5237 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5240 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5241 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5244 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5246 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5251 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5252 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5253 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5256 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5257 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5262 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5265 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5267 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5268 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5269 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5276 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5279 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5280 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5292 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5293 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5294 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5295 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5296 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5297 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5300 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5301 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5303 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5304 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5306 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5308 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5310 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5312 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5318 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5319 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5325 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5329 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5334 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5336 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5337 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5339 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
