porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6711 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6720 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6721 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6726 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6727 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6728 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6730 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6731 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6735 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6736 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6737 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6742 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6744 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6747 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6748 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6751 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6752 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6759 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6760 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6761 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6763 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6766 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6767 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6768 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6770 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6771 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6772 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6775 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6776 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6779 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6781 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6787 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6791 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6792 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6793 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6794 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6795 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6797 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6800 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6801 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6802 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6804 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6805 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6808 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6811 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6812 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6816 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6818 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6820 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6821 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6822 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6826 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6827 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6828 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6830 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6832 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6833 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6835 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6836 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6837 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6839 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6842 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6843 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6845 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6848 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6859 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6888 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6891 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6913 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6952 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6957 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6972 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6982 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6983 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6991 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6993 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7033 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7036 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7042 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7048 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7062 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7093 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7112 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7121 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7132 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7146 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7147 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7159 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7160 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7162 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7168 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7174 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7193 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7197 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7213 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7219 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7225 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7226 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7231 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7246 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7254 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7304 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7312 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7330 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7331 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7341 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7380 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7417 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7459 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7463 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7499 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7502 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7535 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7555 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7571 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7580 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7581 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7597 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7606 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7627 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7641 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7642 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7650 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7659 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7662 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7665 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7696 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7711 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7715 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7718 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7728 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7732 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7750 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7752 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7754 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7758 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7762 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7768 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7799 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7809 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7834 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7837 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7869 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7887 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7901 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7970 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7975 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7977 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7984 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8034 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8035 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8046 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8049 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8055 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8062 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8080 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8082 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8100 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8108 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8110 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8125 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8127 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8182 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8193 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8197 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8202 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8209 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8218 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8224 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8273 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8288 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8328 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8338 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8395 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8433 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8434 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8452 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8468 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8490 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8500 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8503 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8520 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8562 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8611 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8615 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8642 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8645 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8685 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8695 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8732 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8743 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8745 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8756 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8773 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8790 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8792 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
