porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8801 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8803 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8805 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8806 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8820 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8821 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8830 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8839 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8867 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8873 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8881 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8885 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8911 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8914 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8918 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8942 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8960 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8973 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8979 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8986 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8988 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8998 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9025 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9049 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9058 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9078 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9080 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9102 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9126 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9127 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9133 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9134 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9136 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9144 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9145 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9152 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9164 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9167 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9172 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9198 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9205 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9208 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9210 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9211 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9214 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9224 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9232 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9237 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9240 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9244 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9245 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9249 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9254 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9255 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9258 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9259 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9261 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9268 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9269 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9274 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9276 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9285 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9298 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9300 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9304 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9310 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9313 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9318 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9324 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9325 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9326 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9328 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9332 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9333 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9341 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9344 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9345 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9353 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9354 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9357 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9360 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9361 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9365 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9367 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9374 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9375 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9376 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9377 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9393 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9394 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9395 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9396 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9399 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9403 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9409 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9411 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9413 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9417 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9418 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9419 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9429 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9430 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9436 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9437 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9445 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9451 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9453 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9462 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9470 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9471 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9475 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9484 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9487 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9491 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9494 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9495 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9496 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9497 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9499 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9502 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9517 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9520 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9523 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9525 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9531 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9534 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9540 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9541 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9547 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9549 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9558 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9563 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9566 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9575 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9583 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9585 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9588 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9596 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9601 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9604 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9606 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9611 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9616 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9618 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9620 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9622 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9627 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9630 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9638 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9647 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9649 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9651 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9654 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9679 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9680 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9689 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9692 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9694 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9700 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9706 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9713 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9714 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9720 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9721 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9728 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9729 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9732 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9741 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9744 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9750 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9754 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9760 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9761 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9762 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9769 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9773 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9778 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9780 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9784 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9787 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9790 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9794 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9796 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9797 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9800 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9801 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9803 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9806 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9808 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9809 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9812 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9813 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9816 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9818 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9821 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9823 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
