porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 3934 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 3947 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 3949 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 3958 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 3967 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 3983 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4004 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4013 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4014 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4015 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4056 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4059 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4070 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4073 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4076 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4097 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4109 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4113 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4133 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4137 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4145 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4146 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4147 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4160 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4182 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4187 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4204 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4218 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4219 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4221 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4232 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4247 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4251 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4252 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4253 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4254 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4260 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4318 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4326 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4351 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4356 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4370 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4373 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4379 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4381 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4384 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4386 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4388 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4392 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4402 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4419 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4446 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4447 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4471 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4473 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4478 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4483 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4488 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4494 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4497 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4518 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4523 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4541 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4551 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4557 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4559 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4567 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4569 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4572 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4573 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4574 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4576 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4577 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4579 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4580 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4581 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4582 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4583 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4584 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4589 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4591 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4592 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4593 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4595 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4600 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4601 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4603 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4609 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4611 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4612 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4613 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4615 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4616 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4620 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4621 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4622 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4625 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4626 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4628 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4629 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4631 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4633 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4635 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4637 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4641 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4644 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4646 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4647 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4651 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4654 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4655 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4658 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4660 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4661 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4667 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4669 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4670 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4671 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4672 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4673 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4675 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4676 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4679 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4680 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4686 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4688 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4692 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4695 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4699 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4702 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4705 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4715 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4716 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4717 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4718 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4719 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4729 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4730 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4732 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4733 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4736 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4739 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4744 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4745 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4746 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4752 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4754 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4757 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4758 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4763 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4766 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4767 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4768 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4769 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4771 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4773 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4774 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4775 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4778 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4779 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4784 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4787 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4788 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4789 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4791 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4792 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4793 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4794 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4801 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4803 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4805 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4808 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4810 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4812 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4813 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4814 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4816 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4818 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4824 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4826 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4828 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4829 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4830 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4831 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4836 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4837 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4838 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4845 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4846 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4849 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4851 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4852 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4853 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4856 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4858 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4860 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
