porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 3 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 4 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 5 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 6 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 7 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 8 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 9 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 10 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 11 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 12 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 13 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 14 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 15 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 16 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 17 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 18 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 19 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 20 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 21 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 22 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 23 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 24 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 25 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 26 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 27 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 28 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 29 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 30 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 31 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 32 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 33 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 34 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 35 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 36 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 37 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 38 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 39 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 40 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 41 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 42 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 43 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 44 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 45 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 46 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 47 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 48 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 49 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 50 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 51 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 52 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 53 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 54 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 55 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 56 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 57 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 58 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 59 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 60 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 61 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 62 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 63 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 64 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 65 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 66 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 67 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 68 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 767 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 773 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 774 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 795 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 797 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 799 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 843 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 846 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 863 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 886 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 891 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 892 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 895 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 897 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 908 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 909 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 931 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 941 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 954 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 971 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 976 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 980 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 981 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 988 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1001 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1003 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1017 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1038 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1045 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1046 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1049 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1062 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1085 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1098 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1125 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1153 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1155 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1162 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1164 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1168 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1172 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1187 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1192 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1238 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1277 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1293 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1317 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1319 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1359 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1361 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1367 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1372 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1374 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1375 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1384 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1397 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1399 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1409 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1419 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1429 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1436 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1437 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1438 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1440 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1444 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1448 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1449 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1454 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1467 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1470 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1485 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1491 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1502 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1504 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1507 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1517 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1518 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1545 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1549 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1571 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1573 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1579 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1587 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1607 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1627 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1641 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1664 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1672 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1682 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1687 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1700 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1728 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1736 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1745 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1768 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1770 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1779 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1792 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1794 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1796 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1797 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1810 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1838 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1842 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1850 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1878 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1885 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1888 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1914 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1932 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1935 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1938 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1943 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1951 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1955 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1957 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1960 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1963 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1977 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 1980 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2004 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2010 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2025 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2043 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2052 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2054 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2075 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
porthomclPairsOrthologs.py -t /home/meiker/orthomcl/taxon_list -b /home/meiker/orthomcl/besthit -o /home/meiker/orthomcl/orthologs -x 2076 -l /home/meiker/orthomcl/logs/08042020_logfile_orthologs.txt
