#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 17 14:03:12 2020

@author: meike
"""

'''
Add 24 genomes to metatable and database_id table.
'''

import os
from pathlib import Path


path = os.getcwd()
p = Path(path)


strepto_id_file = os.path.join(p.parents[0], 'files' , 'streptococcus_patric_id_with_database_id.tsv')

#Add the 24 sequenced genomes to the end of the database to patric id table. Adds column species for the sequenced ones
with open(strepto_id_file) as f:
    with open (os.path.join(p.parents[0], 'files', 'sequenced_species_name_list')) as f2:
        with open(os.path.join(p.parents[0], 'files' , '17012020streptococcus_patric_id_with_database_id.tsv'), 'w') as f3:
            headers = f.readline().strip().split('\t')
            headers.append('species')
            f3.write('\t'.join(headers)+'\n')
            for line in f:
                a = line.strip().split('\t')
                f3.write('\t'.join(a)+'\n')
            last_id = a[0]    
            last_id = last_id.split('_')
            species = []
            for line in f2:
                line= line.strip()
                species.append(line)
            new_db_ids = []
            for i in range(len(species)):
                db_id = last_id[0]+'_'+ str(int(last_id[1])+i+1)
                new_db_ids.append(db_id)
                f3.write('\t'.join([db_id, '', species[i], '\n']))
                 
#Add genomes to database table
with open(os.path.join(p.parents[0], 'files' , '06012020_streptococcus_database.tsv')) as f:
    with open(os.path.join(p.parents[0], 'files' , '17012020_streptococcus_database.tsv'), 'w') as f2:
        headers = f.readline().strip().split('\t')
        headers_inds = {i : name for name, i in enumerate(headers)}
        
        db_index = headers_inds['database_id']
        species_index = headers_inds['species']
        
        f2.write('\t'.join(headers)+'\n')
        for line in f:
            a = line.strip().split('\t')
            number_columns = len(a)
            f2.write(line)
            
        #make new lines to add db_id and species to right columns
        for i in range(len(species)):
            newline = ['']*number_columns
            newline[db_index] = new_db_ids[i]
            newline[species_index] = species[i]
            f2.write('\t'.join(newline)+'\n')
            
