prokka /home/meiker/git/genomes/lactococcus_00001.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00001 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00002.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00002 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00003.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00003 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00004.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00004 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00005.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00005 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00006.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00006 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00007.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00007 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00008.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00008 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00009.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00009 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00010.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00010 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00011.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00011 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00012.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00012 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00013.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00013 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00014.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00014 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00015.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00015 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00016.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00016 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00017.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00017 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00018.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00018 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00019.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00019 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00020.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00020 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00021.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00021 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00022.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00022 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00023.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00023 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00024.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00024 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00025.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00025 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00026.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00026 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00027.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00027 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00028.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00028 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00029.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00029 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00030.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00030 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00031.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00031 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00032.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00032 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00033.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00033 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00034.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00034 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00035.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00035 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00036.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00036 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00037.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00037 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00038.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00038 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00039.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00039 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00040.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00040 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00041.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00041 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00042.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00042 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00043.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00043 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00044.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00044 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00045.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00045 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00046.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00046 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00047.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00047 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00048.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00048 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00049.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00049 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00050.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00050 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00051.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00051 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00052.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00052 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00053.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00053 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00054.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00054 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00055.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00055 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00056.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00056 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00057.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00057 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00058.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00058 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00059.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00059 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00060.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00060 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00061.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00061 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00062.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00062 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00063.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00063 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00064.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00064 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00065.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00065 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00066.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00066 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00067.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00067 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00068.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00068 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00069.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00069 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00070.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00070 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00071.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00071 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00072.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00072 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00073.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00073 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00074.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00074 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00075.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00075 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00076.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00076 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00077.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00077 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00078.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00078 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00079.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00079 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00080.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00080 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00081.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00081 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00082.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00082 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00083.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00083 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00084.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00084 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00085.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00085 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00086.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00086 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00087.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00087 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00088.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00088 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00089.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00089 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00090.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00090 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00091.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00091 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00092.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00092 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00093.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00093 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00094.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00094 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00095.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00095 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00096.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00096 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00097.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00097 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00098.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00098 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00099.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00099 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00100.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00100 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00101.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00101 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00102.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00102 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00103.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00103 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00104.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00104 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00105.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00105 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00106.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00106 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00107.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00107 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00108.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00108 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00109.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00109 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00110.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00110 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00111.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00111 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00112.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00112 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00113.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00113 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00114.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00114 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00115.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00115 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00116.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00116 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00117.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00117 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00118.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00118 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00119.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00119 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00120.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00120 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00121.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00121 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00122.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00122 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00123.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00123 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00124.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00124 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00125.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00125 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00126.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00126 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00127.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00127 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00128.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00128 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00129.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00129 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00130.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00130 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00131.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00131 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00132.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00132 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00133.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00133 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00134.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00134 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00135.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00135 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00136.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00136 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00137.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00137 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00138.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00138 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00139.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00139 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00140.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00140 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00141.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00141 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00142.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00142 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00143.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00143 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00144.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00144 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00145.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00145 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00146.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00146 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00147.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00147 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00148.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00148 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00149.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00149 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00150.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00150 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00151.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00151 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00152.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00152 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00153.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00153 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00154.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00154 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00155.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00155 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00156.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00156 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00157.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00157 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00158.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00158 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00159.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00159 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00160.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00160 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00161.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00161 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00162.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00162 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00163.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00163 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00164.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00164 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00165.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00165 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00166.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00166 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00167.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00167 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00168.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00168 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00169.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00169 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00170.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00170 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00171.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00171 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00172.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00172 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00173.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00173 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00174.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00174 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00175.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00175 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00176.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00176 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00177.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00177 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00178.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00178 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00179.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00179 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00180.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00180 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00181.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00181 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00182.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00182 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00183.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00183 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00184.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00184 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00185.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00185 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00186.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00186 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00187.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00187 --genus Lactococcus
prokka /home/meiker/git/genomes/lactococcus_00188.fna --outdir /home/meiker/git/prokka_annotation --prefix lactococcus_00188 --genus Lactococcus
