#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  3 09:56:44 2020

@author: meike
"""

'''
Building phylogenetic tree based on HMM profiles 
'''

import os
from pathlib import Path

path = os.getcwd()
p = Path(path)
#%%

'''
Homology search for each proteome using 71 HMM profiles.
Use --tblout to save a parseble table which is used to determine the best hit.
Use -o to output a file from which the alignment from the protein sequence to the profile can be
'''

profiles = '/home/meiker/phylo_tree/genes.hmm'
output_path = '/home/meiker/phylo_tree/output_hmm/'
files_dir = '/home/meiker/git/data/prokka_annotation/'

db_ids = []
with open (os.path.join(p.parents[0], 'files', 'taxon_list')) as f:
    for line in f:
        a = line.strip()
        db_ids.append(a)

with open (os.path.join(p.parents[0],'scripts', 'bash_scripts', 'pyhlogenetic_tree', 'get_hmm_search.sh'), 'w') as f:
    for id_ in db_ids:
        f.write('hmmsearch --tblout '+ output_path + 'hmm/'+id_+'.txt -o '+ output_path+'hmmalign/'+id_+' --cut_tc --cpu 8 ' + profiles + ' ' + files_dir + id_ + '/'+ id_ +'.faa\n\n')
                


