porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09023.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09023.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05215.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05215.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10982.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10982.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05123.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05123.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03132.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03132.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00085.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00085.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06013.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06013.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04318.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04318.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02294.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02294.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01758.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01758.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05304.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05304.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10030.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10030.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05115.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05115.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00962.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00962.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07212.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07212.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11384.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11384.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08633.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08633.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06054.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06054.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07669.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07669.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05755.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05755.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09122.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09122.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10851.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10851.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04750.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04750.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06496.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06496.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05633.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05633.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00086.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00086.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03357.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03357.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04332.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04332.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02822.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02822.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05121.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05121.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10059.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10059.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01583.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01583.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11532.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11532.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05948.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05948.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07258.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07258.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00697.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00697.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05370.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05370.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08379.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08379.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09066.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09066.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07700.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07700.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04803.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04803.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10905.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10905.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06400.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06400.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05513.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05513.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10291.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10291.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02497.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02497.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03816.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03816.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04563.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04563.ss.tsv
