porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05013.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05013.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03760.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03760.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02800.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02800.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05369.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05369.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09101.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09101.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10980.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10980.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06198.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06198.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04840.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04840.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00079.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00079.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00927.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00927.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02035.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02035.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05542.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05542.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06184.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06184.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06919.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06919.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10339.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10339.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11369.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11369.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08176.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08176.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04912.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04912.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08763.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08763.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03373.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03373.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05710.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05710.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09292.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09292.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03930.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03930.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10587.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10587.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06083.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06083.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02454.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02454.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04531.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04531.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05823.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05823.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00925.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00925.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01882.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01882.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10289.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10289.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06085.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06085.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11664.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11664.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00080.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00080.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05097.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05097.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06900.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06900.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05497.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05497.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07822.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07822.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09549.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09549.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10540.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10540.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08823.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08823.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06526.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06526.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03177.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03177.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04417.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04417.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04076.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04076.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05821.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05821.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00793.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00793.ss.tsv
