porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01876.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01876.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05417.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05417.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10889.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10889.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07046.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07046.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07491.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07491.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04500.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04500.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06182.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06182.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03580.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03580.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08560.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08560.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10179.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10179.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00077.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00077.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05751.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05751.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11256.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11256.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04244.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04244.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02383.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02383.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06389.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06389.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04869.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04869.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01181.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01181.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09127.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09127.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10732.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10732.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01517.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01517.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05741.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05741.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07222.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07222.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05033.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05033.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06543.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06543.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03125.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03125.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10361.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10361.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11624.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11624.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05421.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05421.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02258.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02258.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00078.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00078.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09361.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09361.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06404.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06404.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05094.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05094.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00794.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00794.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10750.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10750.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01661.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01661.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05629.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05629.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07096.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07096.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07640.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07640.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05979.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05979.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09941.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09941.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08699.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08699.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11692.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11692.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03419.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03419.ss.tsv
