porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00087.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00087.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02868.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02868.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11560.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11560.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05771.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05771.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06862.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06862.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09232.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09232.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06415.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06415.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11025.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11025.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01257.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01257.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07857.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07857.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05101.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05101.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08474.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08474.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05688.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05688.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06407.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06407.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09785.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09785.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11880.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11880.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02340.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02340.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02998.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02998.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03843.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03843.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00088.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00088.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05168.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05168.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09072.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09072.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02042.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02042.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05938.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05938.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10709.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10709.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07346.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07346.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01282.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01282.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07898.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07898.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08773.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08773.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04957.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04957.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10092.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10092.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06409.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06409.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05781.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05781.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11263.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11263.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08971.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08971.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02795.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02795.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11169.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11169.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03019.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03019.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04376.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04376.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05995.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05995.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05730.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05730.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04652.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04652.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00089.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00089.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01925.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01925.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06726.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06726.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09722.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09722.ss.tsv
