porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00780.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00780.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07442.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07442.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05576.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05576.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08864.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08864.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11609.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11609.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06548.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06548.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04775.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04775.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09408.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09408.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10503.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10503.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05699.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05699.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02826.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02826.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03704.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03704.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03092.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03092.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06413.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06413.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10128.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10128.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01584.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01584.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06807.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06807.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04551.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04551.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00090.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00090.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05294.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05294.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00923.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00923.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11773.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11773.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07503.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07503.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06625.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06625.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08201.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08201.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09035.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09035.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11120.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11120.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04982.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04982.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05346.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05346.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06020.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06020.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02607.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02607.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10405.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10405.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03010.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03010.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04054.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04054.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06724.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06724.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02074.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02074.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04878.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04878.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05851.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05851.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11323.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11323.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01033.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01033.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06617.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06617.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08720.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08720.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09413.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09413.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07529.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07529.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10681.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10681.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00091.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00091.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05738.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05738.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04701.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04701.ss.tsv
