porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05932.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05932.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10140.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10140.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05448.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05448.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03161.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03161.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05068.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05068.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01941.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01941.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10711.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10711.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11498.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11498.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07237.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07237.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06077.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06077.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05232.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05232.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00067.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00067.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09260.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09260.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08926.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08926.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02844.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02844.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04672.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04672.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07726.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07726.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03748.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03748.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01274.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01274.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09858.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09858.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05933.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05933.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05687.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05687.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03602.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03602.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04550.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04550.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10720.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10720.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01900.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01900.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05667.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05667.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06391.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06391.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09097.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09097.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11230.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11230.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06994.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06994.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04725.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04725.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08479.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08479.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02683.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02683.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10313.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10313.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08039.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08039.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00068.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00068.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01309.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01309.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03685.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03685.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05569.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05569.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06072.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06072.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11111.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11111.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04833.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04833.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03042.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03042.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09215.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09215.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11847.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11847.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01534.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01534.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05872.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05872.ss.tsv
