porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02125.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02125.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10862.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10862.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03634.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03634.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05882.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05882.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00901.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00901.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04605.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04605.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09898.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09898.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00075.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00075.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11782.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11782.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06498.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06498.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01369.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01369.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06707.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06707.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03036.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03036.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07749.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07749.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05325.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05325.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09381.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09381.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10672.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10672.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04427.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04427.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08877.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08877.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06132.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06132.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02304.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02304.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03952.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03952.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05785.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05785.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04574.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04574.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09988.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09988.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11318.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11318.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06441.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06441.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00926.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00926.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01352.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01352.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09660.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09660.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05752.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05752.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06667.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06667.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10852.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10852.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07717.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07717.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04669.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04669.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03194.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03194.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00076.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00076.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06010.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06010.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08400.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08400.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03835.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03835.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05180.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05180.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02469.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02469.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11775.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11775.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09824.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09824.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04857.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04857.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06296.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06296.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00847.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00847.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08950.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08950.ss.tsv
