porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03554.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03554.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01985.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01985.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05358.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05358.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04861.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04861.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06639.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06639.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07145.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07145.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08737.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08737.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07495.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07495.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09920.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09920.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02662.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02662.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03625.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03625.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05843.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05843.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04396.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04396.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09211.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09211.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00073.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00073.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06338.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06338.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01214.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01214.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10822.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10822.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03074.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03074.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01842.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01842.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05681.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05681.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11643.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11643.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07209.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07209.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05131.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05131.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05956.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05956.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10015.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10015.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07913.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07913.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08511.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08511.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02420.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02420.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09199.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09199.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04359.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04359.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05838.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05838.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10606.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10606.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04941.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04941.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01180.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01180.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06024.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06024.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00074.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00074.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01757.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01757.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10221.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10221.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11307.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11307.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03216.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03216.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05281.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05281.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08052.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08052.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07314.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07314.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04561.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04561.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08760.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08760.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06439.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06439.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09447.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09447.ss.tsv
