porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05743.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05743.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06777.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06777.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05936.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05936.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07825.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07825.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08544.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08544.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05853.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05853.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09752.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09752.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04818.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04818.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11557.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11557.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00083.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00083.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03595.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03595.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03770.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03770.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06274.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06274.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02275.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02275.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01654.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01654.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09194.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09194.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10625.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10625.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00640.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00640.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05474.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05474.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04856.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04856.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06986.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06986.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06035.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06035.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05773.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05773.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08194.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08194.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07515.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07515.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10159.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10159.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04819.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04819.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11819.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11819.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06069.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06069.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09188.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09188.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00084.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00084.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05661.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05661.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03024.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03024.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10829.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10829.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03650.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03650.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04420.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04420.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02220.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02220.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01568.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01568.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06033.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06033.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00643.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00643.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05228.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05228.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07148.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07148.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10431.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10431.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04450.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04450.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11306.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11306.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08279.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08279.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06099.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06099.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08180.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08180.ss.tsv
