porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06396.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06396.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10373.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10373.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05016.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05016.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11879.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11879.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01690.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01690.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05810.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05810.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09011.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09011.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06886.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06886.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00081.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00081.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05911.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05911.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07558.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07558.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04530.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04530.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08392.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08392.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05835.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05835.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03232.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03232.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04096.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04096.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06452.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06452.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02435.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02435.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10112.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10112.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00995.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00995.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04593.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04593.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11543.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11543.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05205.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05205.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01861.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01861.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09540.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09540.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11048.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11048.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06831.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06831.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05069.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05069.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05845.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05845.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07465.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07465.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08296.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08296.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06426.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06426.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03523.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03523.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00082.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00082.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10395.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10395.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04801.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04801.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05779.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05779.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03910.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03910.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11449.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11449.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02305.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02305.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02083.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02083.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00774.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00774.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06559.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06559.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09208.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09208.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10809.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10809.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04910.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04910.ss.tsv
