porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03875.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03875.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06403.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06403.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11279.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11279.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04533.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04533.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03522.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03522.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10068.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10068.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01978.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01978.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05648.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05648.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06533.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06533.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07413.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07413.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00071.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00071.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08730.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08730.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11074.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11074.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09553.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09553.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08038.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08038.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04970.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04970.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02425.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02425.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05793.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05793.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05945.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05945.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11740.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11740.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03785.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03785.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01176.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01176.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04487.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04487.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10403.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10403.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05805.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05805.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06461.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06461.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09454.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09454.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03121.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03121.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01341.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01341.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10827.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10827.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04709.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04709.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06996.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06996.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05753.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05753.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06325.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06325.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08523.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08523.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07995.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07995.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00072.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00072.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02249.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02249.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11606.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11606.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10149.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10149.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04522.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04522.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04335.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04335.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05198.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05198.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06149.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06149.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01076.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01076.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10719.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10719.ss.tsv
