porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06389.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06389.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04869.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04869.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01181.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01181.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09127.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09127.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10732.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10732.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01517.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01517.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05741.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05741.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07222.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07222.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05033.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05033.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06543.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06543.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03125.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03125.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10361.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10361.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11624.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11624.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05421.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05421.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02258.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02258.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00078.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00078.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09361.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09361.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06404.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06404.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05094.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05094.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00794.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00794.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10750.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10750.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01661.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01661.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05629.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05629.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07096.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07096.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07640.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07640.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05979.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05979.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09941.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09941.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08699.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08699.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11692.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11692.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03419.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03419.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05013.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05013.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03760.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03760.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02800.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02800.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05369.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05369.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09101.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09101.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10980.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10980.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06198.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06198.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04840.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04840.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00079.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00079.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00927.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00927.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02035.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02035.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05542.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05542.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06184.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06184.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06919.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06919.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10339.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10339.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11369.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11369.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08176.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08176.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04912.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04912.ss.tsv
