porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03036.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03036.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07749.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07749.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05325.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05325.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09381.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09381.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10672.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10672.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04427.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04427.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08877.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08877.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06132.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06132.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02304.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02304.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03952.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03952.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05785.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05785.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04574.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04574.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09988.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09988.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11318.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11318.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06441.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06441.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00926.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00926.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01352.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01352.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09660.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09660.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05752.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05752.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06667.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06667.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10852.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10852.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07717.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07717.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04669.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04669.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03194.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03194.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00076.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00076.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06010.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06010.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08400.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08400.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03835.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03835.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05180.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05180.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02469.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02469.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11775.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11775.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09824.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09824.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04857.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04857.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06296.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06296.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00847.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00847.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08950.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08950.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01876.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01876.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05417.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05417.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10889.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10889.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07046.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07046.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07491.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07491.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04500.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04500.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06182.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06182.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03580.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03580.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08560.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08560.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10179.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10179.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00077.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00077.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05751.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05751.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11256.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11256.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04244.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04244.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02383.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02383.ss.tsv
