porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04593.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04593.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11543.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11543.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05205.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05205.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01861.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01861.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09540.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09540.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11048.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11048.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06831.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06831.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05069.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05069.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05845.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05845.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07465.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07465.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08296.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08296.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06426.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06426.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03523.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03523.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00082.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00082.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10395.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10395.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04801.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04801.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05779.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05779.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03910.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03910.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11449.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11449.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02305.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02305.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02083.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02083.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00774.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00774.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06559.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06559.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09208.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09208.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10809.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10809.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04910.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04910.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05743.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05743.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06777.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06777.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05936.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05936.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07825.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07825.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08544.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08544.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05853.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05853.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09752.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09752.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04818.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04818.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11557.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11557.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00083.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00083.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03595.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03595.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03770.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03770.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06274.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06274.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02275.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02275.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01654.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01654.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09194.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09194.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10625.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10625.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00640.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00640.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05474.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05474.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04856.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04856.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06986.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06986.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06035.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06035.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05773.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05773.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08194.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08194.ss.tsv
