porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09729.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09729.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04787.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04787.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02349.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02349.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07796.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07796.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06323.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06323.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10875.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10875.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00916.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00916.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03940.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03940.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05321.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05321.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00069.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00069.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08972.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08972.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05082.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05082.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03353.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03353.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11421.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11421.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01860.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01860.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05964.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05964.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05255.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05255.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09732.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09732.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06665.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06665.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08915.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08915.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05041.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05041.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02386.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02386.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08017.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08017.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10476.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10476.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04130.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04130.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06110.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06110.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00860.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00860.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05772.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05772.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09358.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09358.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00070.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00070.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11649.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11649.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05014.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05014.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03057.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03057.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01621.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01621.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09921.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09921.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06579.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06579.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05536.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05536.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07155.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07155.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08499.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08499.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08119.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08119.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10549.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10549.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05058.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05058.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02586.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02586.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09501.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09501.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05499.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05499.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03875.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03875.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06403.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06403.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11279.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11279.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04533.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04533.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03522.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03522.ss.tsv
