porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04332.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04332.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02822.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02822.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05121.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05121.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10059.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10059.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01583.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01583.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11532.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11532.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05948.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05948.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07258.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07258.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00697.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00697.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05370.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05370.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08379.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08379.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09066.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09066.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07700.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07700.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04803.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04803.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10905.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10905.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06400.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06400.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05513.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05513.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10291.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10291.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02497.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02497.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03816.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03816.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04563.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04563.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00087.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00087.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02868.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02868.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11560.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11560.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05771.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05771.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06862.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06862.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09232.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09232.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06415.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06415.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11025.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11025.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01257.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01257.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07857.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07857.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05101.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05101.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08474.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08474.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05688.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05688.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06407.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06407.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09785.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09785.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11880.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11880.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02340.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02340.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02998.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02998.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03843.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03843.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00088.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00088.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05168.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05168.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09072.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09072.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02042.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02042.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05938.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05938.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10709.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10709.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07346.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07346.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01282.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01282.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07898.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07898.ss.tsv
