porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07515.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07515.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10159.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10159.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04819.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04819.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11819.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11819.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06069.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06069.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09188.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09188.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00084.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00084.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05661.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05661.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03024.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03024.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10829.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10829.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03650.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03650.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04420.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04420.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02220.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02220.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01568.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01568.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06033.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06033.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00643.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00643.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05228.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05228.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07148.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07148.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10431.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10431.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04450.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04450.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11306.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11306.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08279.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08279.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06099.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06099.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08180.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08180.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09023.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09023.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05215.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05215.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10982.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10982.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05123.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05123.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03132.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03132.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00085.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00085.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06013.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06013.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04318.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04318.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02294.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02294.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01758.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01758.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05304.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05304.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10030.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10030.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05115.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05115.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00962.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00962.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07212.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07212.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11384.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11384.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08633.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08633.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06054.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06054.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07669.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07669.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05755.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05755.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09122.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09122.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10851.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10851.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04750.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04750.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06496.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06496.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05633.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05633.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00086.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00086.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03357.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03357.ss.tsv
