porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04054.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04054.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06724.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06724.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02074.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02074.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04878.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04878.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05851.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05851.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11323.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11323.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01033.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01033.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06617.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06617.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08720.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08720.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09413.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09413.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07529.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07529.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10681.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10681.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00091.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00091.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05738.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05738.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04701.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04701.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09821.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09821.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03099.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03099.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06295.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06295.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02159.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02159.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07180.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07180.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05444.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05444.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11941.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11941.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04251.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04251.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01415.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01415.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04501.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04501.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09629.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09629.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00898.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00898.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10934.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10934.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05908.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05908.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07485.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07485.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08424.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08424.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05731.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05731.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10249.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10249.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04747.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04747.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00092.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00092.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03009.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03009.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05930.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05930.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02641.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02641.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06890.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06890.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11509.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11509.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05337.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05337.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09508.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09508.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01550.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01550.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04206.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04206.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04612.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04612.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11212.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11212.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01276.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01276.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08087.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08087.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08225.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08225.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06159.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06159.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10122.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10122.ss.tsv
