porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08763.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08763.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03373.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03373.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05710.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05710.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09292.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09292.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03930.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03930.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10587.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10587.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06083.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06083.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02454.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02454.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04531.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04531.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05823.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05823.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00925.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00925.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01882.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01882.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10289.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10289.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06085.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06085.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11664.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11664.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00080.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00080.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05097.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05097.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06900.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06900.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05497.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05497.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07822.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07822.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09549.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09549.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10540.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10540.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08823.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08823.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06526.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06526.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03177.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03177.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04417.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04417.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04076.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04076.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05821.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05821.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00793.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00793.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06396.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06396.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10373.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10373.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05016.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05016.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11879.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11879.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01690.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01690.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05810.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05810.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09011.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09011.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06886.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06886.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00081.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00081.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05911.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05911.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07558.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07558.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04530.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04530.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08392.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08392.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05835.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05835.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03232.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03232.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04096.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04096.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06452.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06452.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02435.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02435.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10112.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10112.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00995.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00995.ss.tsv
