porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08868.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08868.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09411.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09411.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11765.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11765.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10695.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10695.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05275.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05275.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06451.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06451.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04556.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04556.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06957.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06957.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08098.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08098.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09837.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09837.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06250.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06250.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05482.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05482.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04711.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04711.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09246.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09246.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08630.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08630.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11652.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11652.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06000.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06000.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05479.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05479.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11159.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11159.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04567.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04567.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06931.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06931.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06277.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06277.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09720.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09720.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05686.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05686.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04670.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04670.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07679.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07679.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09280.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09280.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11290.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11290.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06253.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06253.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05847.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05847.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04813.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04813.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10567.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10567.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08640.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08640.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06922.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06922.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09794.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09794.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06652.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06652.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04611.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04611.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05639.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05639.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08943.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08943.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07935.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07935.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11763.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11763.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06361.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06361.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04382.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04382.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05567.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05567.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10680.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10680.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08611.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08611.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06792.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06792.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10058.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10058.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06259.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06259.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04870.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04870.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05523.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05523.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09154.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09154.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08138.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08138.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11310.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11310.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05638.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05638.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06585.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06585.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04889.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04889.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10554.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10554.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10432.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10432.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05665.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05665.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06402.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06402.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08770.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08770.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04839.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04839.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07003.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07003.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09223.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09223.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05854.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05854.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05946.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05946.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05066.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05066.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07451.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07451.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10632.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10632.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10019.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10019.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05651.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05651.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05957.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05957.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04529.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04529.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08583.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08583.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06984.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06984.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09050.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09050.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05384.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05384.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11647.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11647.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10541.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10541.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04949.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04949.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06344.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06344.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07711.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07711.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10088.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10088.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05668.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05668.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04810.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04810.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07391.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07391.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08912.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08912.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09657.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09657.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06487.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06487.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11278.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11278.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11163.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11163.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05539.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05539.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05020.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05020.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10357.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10357.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08083.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08083.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06091.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06091.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05290.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05290.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09385.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09385.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04699.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04699.ss.tsv
