porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06430.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06430.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05075.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05075.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10904.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10904.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05503.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05503.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09307.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09307.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11524.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11524.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06408.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06408.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04583.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04583.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09730.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09730.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05459.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05459.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10702.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10702.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06048.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06048.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04945.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04945.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09646.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09646.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05683.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05683.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11274.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11274.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10191.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10191.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06208.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06208.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04749.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04749.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10553.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10553.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05676.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05676.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09167.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09167.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06589.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06589.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04868.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04868.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11743.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11743.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10066.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10066.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05858.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05858.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06026.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06026.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10891.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10891.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04691.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04691.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09297.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09297.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05201.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05201.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06622.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06622.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11803.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11803.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10012.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10012.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04568.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04568.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05530.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05530.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06472.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06472.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10818.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10818.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09142.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09142.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05105.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05105.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05890.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05890.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11861.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11861.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06241.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06241.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10422.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10422.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04980.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04980.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05260.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05260.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10962.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10962.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06538.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06538.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09120.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09120.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04693.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04693.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05366.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05366.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11465.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11465.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10027.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10027.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06484.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06484.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04903.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04903.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05420.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05420.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10989.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10989.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09597.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09597.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06455.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06455.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04985.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04985.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11917.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11917.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09740.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09740.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05717.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05717.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06481.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06481.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04655.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04655.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09579.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09579.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11202.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11202.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05266.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05266.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06090.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06090.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10338.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10338.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11637.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11637.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04662.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04662.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09078.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09078.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11166.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11166.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05153.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05153.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06582.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06582.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10299.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10299.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11519.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11519.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04799.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04799.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09240.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09240.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05675.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05675.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10792.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10792.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09787.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09787.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05961.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05961.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11767.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11767.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04663.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04663.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09510.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09510.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05165.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05165.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10791.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10791.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10024.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10024.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11703.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11703.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06645.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06645.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04827.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04827.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11173.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11173.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05372.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05372.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09767.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09767.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11362.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11362.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05971.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05971.ss.tsv
