porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00053.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00053.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07780.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07780.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02549.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02549.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09835.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09835.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09186.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09186.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10797.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10797.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04601.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04601.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03113.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03113.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05839.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05839.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06653.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06653.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01127.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01127.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08859.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08859.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11510.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11510.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07227.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07227.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01887.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01887.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04708.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04708.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05397.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05397.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06475.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06475.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03663.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03663.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10220.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10220.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04638.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04638.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09697.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09697.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10919.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10919.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07562.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07562.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02770.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02770.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05574.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05574.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03356.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03356.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06586.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06586.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00054.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00054.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11394.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11394.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04528.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04528.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08798.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08798.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01295.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01295.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07064.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07064.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01914.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01914.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05634.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05634.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06109.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06109.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09155.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09155.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10420.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10420.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04925.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04925.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10514.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10514.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04061.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04061.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05616.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05616.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07460.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07460.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06510.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06510.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02346.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02346.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11486.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11486.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04666.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04666.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03252.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03252.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05795.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05795.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00055.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00055.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08808.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08808.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06236.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06236.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00935.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00935.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07029.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07029.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10142.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10142.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09054.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09054.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01853.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01853.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04978.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04978.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11042.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11042.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05253.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05253.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06405.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06405.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04180.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04180.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07787.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07787.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05063.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05063.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11838.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11838.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02614.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02614.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05679.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05679.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05999.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05999.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03034.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03034.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08495.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08495.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09395.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09395.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09861.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09861.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00056.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00056.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07381.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07381.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00859.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00859.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04953.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04953.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02092.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02092.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10847.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10847.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05797.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05797.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06647.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06647.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08028.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08028.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04166.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04166.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11599.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11599.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05247.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05247.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04757.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04757.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06175.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06175.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10319.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10319.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09464.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09464.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08936.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08936.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03006.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03006.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05553.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05553.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04989.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04989.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11062.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11062.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00057.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00057.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06803.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06803.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06435.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06435.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01250.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01250.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01497.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01497.ss.tsv
