porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11845.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11845.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09572.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09572.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05111.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05111.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01312.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01312.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05982.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05982.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03336.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03336.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05789.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05789.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01745.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01745.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00045.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00045.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04439.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04439.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07472.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07472.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06233.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06233.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08616.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08616.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04256.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04256.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05488.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05488.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10857.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10857.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07114.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07114.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10008.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10008.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11502.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11502.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02096.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02096.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09047.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09047.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04774.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04774.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06537.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06537.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01129.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01129.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05172.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05172.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03538.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03538.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06017.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06017.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04634.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04634.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01620.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01620.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10478.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10478.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05154.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05154.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07564.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07564.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08555.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08555.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00046.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00046.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09817.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09817.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06872.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06872.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09304.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09304.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04064.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04064.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11446.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11446.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05906.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05906.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04456.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04456.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05175.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05175.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02283.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02283.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01328.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01328.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05925.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05925.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04841.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04841.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03263.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03263.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05505.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05505.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10496.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10496.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07794.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07794.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01959.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01959.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09889.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09889.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08452.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08452.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09312.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09312.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11482.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11482.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06573.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06573.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04435.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04435.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05259.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05259.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07151.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07151.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03943.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03943.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00047.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00047.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02122.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02122.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00798.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00798.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05560.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05560.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06256.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06256.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05078.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05078.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11001.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11001.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03388.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03388.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10082.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10082.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07937.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07937.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09656.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09656.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11579.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11579.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01555.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01555.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08649.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08649.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05328.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05328.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06723.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06723.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06269.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06269.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04732.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04732.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03643.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03643.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00048.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00048.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02286.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02286.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10987.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10987.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05825.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05825.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01209.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01209.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09866.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09866.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06383.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06383.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04457.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04457.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03028.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03028.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09414.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09414.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11521.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11521.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07578.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07578.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01602.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01602.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05477.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05477.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07140.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07140.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08455.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08455.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06205.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06205.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04379.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04379.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04062.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04062.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11145.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11145.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05584.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05584.ss.tsv
