porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06942.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06942.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08243.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08243.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06263.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06263.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10509.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10509.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11907.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11907.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10073.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10073.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05355.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05355.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04527.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04527.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06514.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06514.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09600.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09600.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05709.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05709.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04389.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04389.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11011.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11011.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11721.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11721.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10094.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10094.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06204.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06204.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05537.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05537.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04788.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04788.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09611.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09611.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06377.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06377.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05390.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05390.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11016.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11016.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11889.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11889.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02311.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02311.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01765.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01765.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04798.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04798.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00718.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00718.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09738.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09738.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03757.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03757.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02969.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02969.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06282.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06282.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00033.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00033.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05871.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05871.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09673.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09673.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04470.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04470.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06306.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06306.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05677.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05677.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11182.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11182.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11415.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11415.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09816.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09816.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02377.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02377.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01761.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01761.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04874.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04874.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00673.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00673.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06245.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06245.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04283.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04283.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05381.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05381.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09255.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09255.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02901.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02901.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04432.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04432.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00034.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00034.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06094.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06094.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05865.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05865.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10823.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10823.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11245.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11245.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10428.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10428.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04892.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04892.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06552.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06552.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02094.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02094.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01451.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01451.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05424.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05424.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09163.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09163.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01264.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01264.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04304.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04304.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03378.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03378.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04656.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04656.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06266.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06266.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05484.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05484.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10888.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10888.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11673.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11673.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10060.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10060.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00035.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00035.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04477.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04477.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06512.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06512.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05246.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05246.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09357.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09357.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02344.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02344.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01968.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01968.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04710.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04710.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03768.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03768.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00790.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00790.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06012.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06012.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03259.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03259.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10787.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10787.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11961.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11961.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05314.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05314.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10325.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10325.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04640.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04640.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09623.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09623.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05920.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05920.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00036.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00036.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05627.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05627.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02251.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02251.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02054.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02054.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10638.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10638.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11884.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11884.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01314.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01314.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04486.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04486.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10138.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10138.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03647.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03647.ss.tsv
