porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02370.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02370.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10353.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10353.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00049.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00049.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09675.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09675.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01103.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01103.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11559.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11559.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03312.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03312.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06272.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06272.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07560.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07560.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04482.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04482.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05169.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05169.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01972.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01972.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08425.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08425.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07007.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07007.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10561.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10561.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06488.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06488.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04042.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04042.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05500.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05500.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09079.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09079.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10286.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10286.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04939.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04939.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02141.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02141.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11295.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11295.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01246.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01246.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00050.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00050.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03005.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03005.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05700.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05700.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06578.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06578.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07845.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07845.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01482.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01482.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08695.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08695.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05107.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05107.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07036.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07036.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10515.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10515.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05824.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05824.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09696.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09696.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10041.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10041.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06540.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06540.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11876.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11876.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03957.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03957.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04817.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04817.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02255.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02255.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05532.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05532.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03601.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03601.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07859.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07859.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00908.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00908.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06112.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06112.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09658.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09658.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04615.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04615.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08728.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08728.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07190.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07190.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01389.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01389.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11015.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11015.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00051.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00051.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05352.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05352.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10100.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10100.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03655.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03655.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11376.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11376.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06120.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06120.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04405.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04405.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05402.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05402.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03489.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03489.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02160.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02160.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07525.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07525.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06530.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06530.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00791.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00791.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09583.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09583.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04865.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04865.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05406.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05406.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10518.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10518.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10461.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10461.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08796.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08796.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02014.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02014.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06970.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06970.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11320.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11320.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06469.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06469.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00052.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00052.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05641.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05641.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04422.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04422.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04063.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04063.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02369.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02369.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06336.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06336.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07452.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07452.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03586.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03586.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05495.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05495.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09247.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09247.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04461.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04461.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10536.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10536.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10021.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10021.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00974.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00974.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08602.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08602.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06420.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06420.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07390.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07390.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01886.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01886.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11492.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11492.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05510.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05510.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04498.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04498.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03793.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03793.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06631.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06631.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05170.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05170.ss.tsv
