porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05970.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05970.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09368.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09368.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05456.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05456.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04678.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04678.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00041.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00041.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06217.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06217.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01474.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01474.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07892.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07892.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03718.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03718.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10580.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10580.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11745.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11745.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05283.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05283.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02350.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02350.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10199.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10199.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04483.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04483.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08313.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08313.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07416.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07416.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00895.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00895.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06214.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06214.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09059.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09059.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03227.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03227.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05428.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05428.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04411.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04411.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06541.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06541.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10502.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10502.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05762.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05762.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11549.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11549.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00042.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00042.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07785.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07785.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01606.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01606.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09969.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09969.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05000.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05000.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04183.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04183.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08677.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08677.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05950.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05950.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02493.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02493.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09185.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09185.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07122.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07122.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05874.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05874.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01087.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01087.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02888.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02888.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05116.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05116.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06646.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06646.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10922.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10922.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05426.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05426.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11329.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11329.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04875.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04875.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07542.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07542.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10372.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10372.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04028.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04028.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05968.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05968.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09128.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09128.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01695.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01695.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08421.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08421.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05780.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05780.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02591.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02591.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00043.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00043.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06698.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06698.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04426.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04426.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01247.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01247.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06234.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06234.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03435.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03435.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05613.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05613.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10970.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10970.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11285.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11285.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04758.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04758.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10014.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10014.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07992.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07992.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09021.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09021.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06330.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06330.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01996.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01996.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03630.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03630.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05586.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05586.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08937.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08937.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04984.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04984.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07141.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07141.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02260.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02260.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06183.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06183.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05498.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05498.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00965.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00965.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00044.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00044.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09795.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09795.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11642.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11642.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10867.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10867.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03577.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03577.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04594.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04594.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06495.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06495.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09699.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09699.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07890.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07890.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05635.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05635.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01835.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01835.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04212.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04212.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08310.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08310.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04694.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04694.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06618.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06618.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07035.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07035.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05291.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05291.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11052.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11052.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10001.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10001.ss.tsv
