porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05323.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05323.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07910.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07910.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11690.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11690.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04399.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04399.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06015.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06015.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04298.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04298.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02673.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02673.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10423.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10423.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09069.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09069.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05783.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05783.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04824.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04824.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02904.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02904.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08752.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08752.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10736.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10736.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06052.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06052.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06793.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06793.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00058.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00058.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01929.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01929.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11368.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11368.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00577.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00577.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05818.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05818.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08019.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08019.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04881.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04881.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05960.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05960.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10254.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10254.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04361.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04361.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09531.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09531.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02197.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02197.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08300.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08300.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05147.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05147.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03214.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03214.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10780.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10780.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06103.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06103.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05118.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05118.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06858.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06858.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11417.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11417.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01660.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01660.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08012.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08012.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08944.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08944.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05410.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05410.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06460.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06460.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00705.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00705.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10238.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10238.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00059.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00059.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04546.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04546.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04229.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04229.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02518.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02518.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10543.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10543.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08330.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08330.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05485.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05485.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06350.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06350.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03585.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03585.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06762.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06762.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11709.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11709.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05011.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05011.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08003.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08003.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09564.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09564.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10234.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10234.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01417.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01417.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00653.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00653.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05812.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05812.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05135.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05135.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06505.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06505.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10932.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10932.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04014.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04014.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00060.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00060.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02164.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02164.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08553.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08553.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11552.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11552.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07312.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07312.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04680.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04680.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05861.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05861.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02935.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02935.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07572.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07572.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09681.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09681.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06517.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06517.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10175.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10175.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02030.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02030.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10546.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10546.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05177.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05177.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04549.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04549.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06051.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06051.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00872.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00872.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08783.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08783.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09305.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09305.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11655.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11655.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02398.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02398.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04128.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04128.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07269.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07269.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00061.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00061.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05749.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05749.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09932.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09932.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07475.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07475.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02955.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02955.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06152.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06152.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04509.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04509.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02051.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02051.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10639.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10639.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05596.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05596.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09175.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09175.ss.tsv
