porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09151.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09151.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04588.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04588.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10975.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10975.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05160.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05160.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09750.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09750.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11926.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11926.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05988.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05988.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09344.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09344.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11006.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11006.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05077.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05077.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05360.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05360.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10392.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10392.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05926.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05926.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09309.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09309.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11153.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11153.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04973.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04973.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05653.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05653.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11292.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11292.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10292.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10292.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06105.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06105.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09110.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09110.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11061.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11061.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05316.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05316.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05067.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05067.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11874.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11874.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10321.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10321.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06038.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06038.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09095.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09095.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10573.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10573.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05435.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05435.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04899.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04899.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10282.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10282.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06621.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06621.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11760.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11760.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08962.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08962.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11185.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11185.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05302.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05302.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04943.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04943.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05909.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05909.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10440.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10440.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11428.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11428.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09570.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09570.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10631.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10631.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05615.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05615.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04604.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04604.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06536.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06536.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10232.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10232.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11584.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11584.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09678.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09678.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05583.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05583.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04410.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04410.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10831.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10831.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06047.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06047.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08034.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08034.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08691.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08691.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07056.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07056.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05650.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05650.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04692.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04692.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10241.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10241.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06490.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06490.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09187.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09187.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11604.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11604.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05732.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05732.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10955.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10955.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04838.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04838.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06649.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06649.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06843.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06843.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07644.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07644.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05595.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05595.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08888.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08888.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04811.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04811.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09980.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09980.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06358.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06358.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09622.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09622.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11841.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11841.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05610.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05610.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10983.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10983.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05002.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05002.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06477.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06477.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05206.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05206.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07365.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07365.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04825.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04825.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07568.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07568.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06164.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06164.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08566.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08566.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10418.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10418.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09285.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09285.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11403.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11403.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05144.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05144.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10552.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10552.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04795.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04795.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06285.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06285.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05467.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05467.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07345.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07345.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04451.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04451.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08007.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08007.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06145.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06145.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10307.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10307.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08205.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08205.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09134.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09134.ss.tsv
