porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05959.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05959.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02991.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02991.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05211.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05211.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09136.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09136.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04744.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04744.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05241.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05241.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06247.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06247.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01983.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01983.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02444.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02444.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00037.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00037.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10786.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10786.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11302.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11302.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09819.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09819.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01258.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01258.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04387.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04387.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03947.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03947.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03534.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03534.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05662.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05662.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06331.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06331.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09205.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09205.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05008.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05008.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10524.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10524.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05655.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05655.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11393.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11393.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06364.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06364.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10124.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10124.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01753.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01753.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02232.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02232.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09448.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09448.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04057.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04057.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04539.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04539.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00856.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00856.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00038.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00038.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05608.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05608.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02871.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02871.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07521.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07521.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07273.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07273.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08789.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08789.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06603.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06603.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10758.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10758.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11779.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11779.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10287.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10287.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04685.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04685.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05447.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05447.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02046.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02046.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06501.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06501.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09651.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09651.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02379.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02379.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03814.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03814.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00813.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00813.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04423.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04423.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08148.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08148.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05704.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05704.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08262.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08262.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00039.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00039.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06846.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06846.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03039.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03039.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05913.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05913.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10694.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10694.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11332.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11332.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09963.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09963.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05051.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05051.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05386.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05386.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05953.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05953.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09108.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09108.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01648.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01648.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02135.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02135.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04794.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04794.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07865.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07865.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05311.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05311.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03880.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03880.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06368.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06368.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00751.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00751.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08505.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08505.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03287.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03287.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06767.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06767.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10957.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10957.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11293.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11293.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10182.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10182.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05226.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05226.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04525.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04525.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/lactococcus_00040.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/lactococcus_00040.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09461.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09461.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05939.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05939.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04578.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04578.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05361.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05361.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01790.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01790.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07619.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07619.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02757.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02757.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06591.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06591.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03956.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03956.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10741.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10741.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11828.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11828.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10396.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10396.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01207.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01207.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05723.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05723.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_07041.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_07041.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04577.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04577.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08613.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08613.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03037.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03037.ss.tsv
