porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_08119.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_08119.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10549.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10549.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05058.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05058.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_02586.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_02586.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_09501.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_09501.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05499.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05499.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03875.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03875.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_06403.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_06403.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_00834.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_00834.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_11279.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_11279.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_04533.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_04533.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_03522.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_03522.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_10068.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_10068.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_01978.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_01978.ss.tsv
porthomclBlastParser /home/meiker/orthomcl/blastres/streptococcus_05648.tab /home/meiker/orthomcl/compliantFasta >> /home/meiker/orthomcl/splitSimSeq/streptococcus_05648.ss.tsv
